services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./Harmonie
      - ./Harmonie/node_modules
      - ./Harmonie/.next
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:13
    env_file: ./Harmonie/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
