services:
  harmonie-nextjs:
    container_name: harmonie-nextjs
    build:
      context: /mnt/user/compose/harmonie
      target: runner
    env_file: /mnt/user/compose/harmonie/Harmonie/.env
    command: npm run start
    environment:
      - NODE_ENV=production
    ports:
      - 7474:7474
    depends_on:
      - harmonie-db
    volumes:
      - /mnt/user/harmonie-data/public:/app/public
      - /mnt/user/harmonie-data/midi-cache:/app/midi-cache
    restart: unless-stopped

  harmonie-db:
    container_name: harmonie-db
    image: postgres:latest
    env_file: /mnt/user/compose/harmonie/Harmonie/.env
    volumes:
      - harmonie-pg-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  harmonie-bmpscrapper:
    container_name: harmonie-bmpscrapper
    build:
      context: /mnt/user/compose/harmonie/bmpscrapper
      dockerfile: Dockerfile
    depends_on:
      - harmonie-db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - /mnt/user/compose/harmonie/bmpscrapper/.env
    restart: unless-stopped

volumes:
  harmonie-pg-data:
