services:
  nextjs:
    container_name: harmonie-nextjs
    build:
      context: .
      target: dev
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - 7474:7474
    depends_on:
      - db
    volumes:
      - ./Harmonie:/app
      - /app/node_modules
      - /app/.next
      - ./Harmonie/public:/app/public
    restart: unless-stopped

  db:
    container_name: harmonie-db
    image: postgres:latest
    env_file: ./Harmonie/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  bmpscrapper:
    container_name: harmonie-bmpscrapper
    build:
      context: ./bmpscrapper
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./bmpscrapper/.env
    restart: unless-stopped

volumes:
  postgres_data:
