services:
  nextjs:
    container_name: harmonie-nextjs
    build:
      context: /mnt/user/compose/harmonie
      target: dev
    command: npm run start
    environment:
      - NODE_ENV=development
    ports:
      - 7474:7474
    depends_on:
      - db
    volumes:
      - /mnt/user/compose/harmonie/Harmonie:/app
      - /app/node_modules
      - /app/.next
      - /mnt/user/harmonie-data:/app/public
    restart: unless-stopped

  db:
    container_name: harmonie-db
    image: postgres:latest
    env_file: /mnt/user/compose/harmonie/Harmonie/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bmpscrapper:
    container_name: harmonie-bmpscrapper
    build:
      context: /mnt/user/compose/harmonie/bmpscrapper
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - /mnt/user/compose/harmonie/bmpscrapper/.env
    restart: unless-stopped

volumes:
  postgres_data:
